services:
  db:
    image: postgres:15
    # container_name: postgres-corfo
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes: {}