paths:
  /login:
    post:
      tags:
        - "auth"
      summary: "Login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: "string"
                  format: "username"
                password:
                  type: "string"
                  format: "password"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  token:
                    type: "string"
        400:
          description: "Bad Request"
        500:
          description: "Internal Server Error"
